### ISSUE TITLE
IE 10 and 11 offer vendor prefixed msToBlob

### ISSUE THREAD

**Issue by AndyOGo** [blueimp/JavaScript-Canvas-to-Blob#33]
Hi,

I'm just curious if IE `10` and `11` vender prefixed version [`msToBlob`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob#Browser_compatibility) has any downside?
If I understand it correctly `msToBlob` seems to only support `image/png` and no quality param at all 🤔

**Comment by blueimp** [comment]
Thanks for the suggestion @AndyOGo.
In addition to the limitations you mentioned, `msToBlob` is also not an async operation.
But it still makes sense to use it if applicable, so I've released a new version.

**Comment by AndyOGo** [comment]
@blueimp 
Ohh wau.
Thanks for your quick answer!
Interesting I didn't know about it being sync only 👍
