### ISSUE TITLE
v2.x to v3.x

### ISSUE THREAD

**Issue by luisjoserivera** [blueimp/JavaScript-Canvas-to-Blob#34]
Hi,
I've been looking for changelogs without success.
No way to know if v3 api has breaking changes

**Comment by luisjoserivera** [comment]
Ignore. This was meant for Blueimp-load-image

**Comment by luisjoserivera** [comment]
Ignore. This was meant for Blueimp-load-image

**Comment by derwaldgeist** [comment]
Well, it applies to this library, too :-)

**Comment by luisjoserivera** [comment]
Indeed
