### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by hiren3897** [blueimp/JavaScript-Canvas-to-Blob#35]
Hello,
When I am trying to use toBlob it gives me " Uncaught (in promise) DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported."

I am trying this : 
```
  // looping through thumbnail list to update thumbnail
                thumbnails.forEach(function(item) {
                    // converting canvas to blob to get short url
                    console.log('canvas', item.canvas)

                    //item.canvas.toBlob(blob => item.data = URL.createObjectURL(blob), 'image/jpeg');
                    if (item.canvas.toBlob) {
                        item.canvas.toBlob(function (blob) {
                            // Do something with the blob object,
                            // e.g. create multipart form data for file uploads:
                            var formData = new FormData()
                            formData.append('file', blob, 'image.jpg')
                            console.log('formData', formData)
                            // ...
                        }, 'image/jpeg')
                    }

                    // deleting unused property
                    delete item.canvas;
                });
```
Do you know why I am facing this issue, OR how can I fix this?

**Comment by BrodaNoel** [comment]
Me too. It seems like in the last version of something (probably last version of Chrome?) the `.toBlob` function gets not polyfied

**Comment by BrodaNoel** [comment]
Fixed doing:

```js
loadImage(
  file,
  (img) => {
    //...
  },
  {
    canvas: true, // <<< The important thing
  }
);
```

**Comment by blueimp** [comment]
@BrodaNoel your issue is unrelated to the tainted image issue @hiren3897 is reporting - I've added a comment to the issue you referenced (https://github.com/blueimp/JavaScript-Load-Image/issues/134), hope that explains things.

@hiren3897 your issue is outside of this library's control, but the following stackoverflow post might help you out:
https://stackoverflow.com/questions/43310565/failto-execute-todataurl-on-htmlcanvaselement
